---
# CentOS-specific tasks
- name: Installing useful packages via YUM
  yum:
    name:
      - vim
      - git
      - wget
      - mtr
      - libselinux-python
      - epel-release
      - bind-utils
      - sysstat
      - nmap
      - jq

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
