---
# Fedora-specific tasks
- name: Installing useful packages via DNF
  dnf:
    name:
    - vim
    - mtr
    - nmap
    - git
    - wget
    - nmap
    - sysstat
    - bind-utils
    - whois
    - python3-pip
    - python3-libselinux
    - jq
    - policycoreutils-python-utils
    - checkpolicy
    - nginx

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
