---
# Fedora-specific tasks
- name: Installing useful packages via DNF
  dnf:
    name:
    - vim
    - mtr
    - nmap
    - git
    - wget
    - nmap
    - sysstat
    - bind-utils
    - whois
    - python3-libselinux
    - jq
    - policycoreutils-python-utils
